home_application/urls.py
# -*- coding: utf-8 -*-
"""testapp URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from home_application import views

urlpatterns = (
    url(r'^$', views.home, name="home"),
    url(r'helloworld/', views.helloworld, name="helloworld"),
    url(r'helloBlueking/', views.helloBlueking, name="helloBlueking"),
    url(r'getModelsData/', views.getModelsData, name="getModelsData"),
    url(r'modelsData/', views.modelsData, name="modelsData"),
    url(r'diskListenerHtml/', views.diskListenerHtml, name="diskListenerHtml"),
    url(r'diskListenerData/', views.diskListenerData, name="diskListenerData"),
    url(r'api/get_disk_usage/', views.api_disk_usage, name="apiDiskUsage"),
    url(r'getUsageData/', views.get_usage_data, name="getUsageData"),

)

urls.py
# -*- coding: utf-8 -*-
"""URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('blueapps.account.urls')),
    # 如果你习惯使用 Django 模板，请在 home_application 里开发你的应用，
    # 这里的 home_application 可以改成你想要的名字
    url(r'^', include('home_application.urls', namespace="framework")),
    # 如果你习惯使用 mako 模板，请在 mako_application 里开发你的应用，
    # 这里的 mako_application 可以改成你想要的名字
    url(r'^mako/', include('mako_application.urls')),
]

home_application/models.py
# -*- coding: utf-8 -*-
from django.db import models
# Create your models here.
class Computer(models.Model):
    name = models.CharField(max_length=64)  # 主机名
    ipCode = models.CharField(max_length=32) #I P地址
    systemType = models.CharField(max_length=16)  # 系统类型
    disk = models.CharField(max_length=16)  # 磁盘
    proportion = models.CharField(max_length=16)  # 使用率
    remarks = models.CharField(max_length=256, null=True)   #备注
    creat_at = models.DateTimeField(auto_now_add=False)
    update_at = models.DateTimeField(auto_now = True)

    # def __unicode__(self):
    #     return self.name

class DiskUsages(models.Model):
    ip = models.CharField('ip地址', max_length=32, default='10.0.1.80')
    system  = models.CharField('系统', max_length=16, default='linux')  # 系统类型
    disk = models.CharField('磁盘', max_length=16, default='usr')  # 磁盘
    file_system = models.CharField('系统文件', max_length=64)
    disk_capacity = models.CharField('磁盘容量', max_length=64)
    disk_used = models.CharField('磁盘已用', max_length=64)
    disk_able = models.CharField('磁盘可用', max_length=64)
    disk_rate = models.CharField('磁盘使用率', max_length=64)
    disk_mount = models.CharField('挂载点', max_length=64)
    add_time = models.DateTimeField('录入时间', auto_now=True, max_length=0)

home_application/views.py
# -*- coding: utf-8 -*-
import datetime
import subprocess, time, json
from django.shortcuts import render,redirect,reverse,HttpResponse
from django.core import serializers
from django.http import JsonResponse
from django.utils import timezone
from blueapps.account.decorators import login_exempt
from blueking.component.shortcuts import get_client_by_user
from home_application import models

# dev.class.o.qcloud.com
# 开发框架中通过中间件默认是需要登录态的，如有不需要登录的，可添加装饰器login_exempt
# 装饰器引入 from blueapps.account.decorators import login_exempt

@login_exempt
def home(request):
    """首页"""
    return render(request, 'home_application/home.html')

@login_exempt
def modelsData(request):
    """"""
    return render(request, 'home_application/modelsData.html')

@login_exempt
def getModelsData(request):
    """helloworld"""
    if request.method == 'POST':  # 当提交post时
        name = request.POST.get('name',None)
        ipCode = request.POST.get('ipCode', None)
        systemType = request.POST.get('optionsRadios', None)
        disk = request.POST.get('disk', None)
        proportion = request.POST.get('proportion', None)
        remarks = request.POST.get('remarks', None)
        creat_at = timezone.now().strftime("%Y-%m-%d %H:%M")
        update_at = timezone.now().strftime("%Y-%m-%d %H:%M")
        obj = models.Computer.objects.create(name=name,ipCode=ipCode,systemType=systemType,disk=disk,proportion=proportion,remarks=remarks,creat_at=creat_at,update_at=update_at)
        obj.save()
    data = {}
    data["catalogues"]={"id":"编号","name":"主机名字","ipCode":"IP地址","systemType":"系统类型","disk":"磁盘信息","proportion":"使用率","remarks":"备注","update_at":"更新时间","creat_at":"创建时间",}
    book = models.Computer.objects.values()
    data["items"] = list(book)
    items = list(book)
    for item in items:
        item["creat_at"] = str(item["creat_at"].strftime("%Y-%m-%d %H:%M"))
        item["update_at"] = str(item["update_at"].strftime("%Y-%m-%d %H:%M"))
    return JsonResponse(data,safe=False)

@login_exempt
def helloworld(request):
    """helloworld"""
    return render(request,'home_application/helloworld.html')

@login_exempt
def helloBlueking(request):
    """helloBlueking"""
    if request.method == 'POST':  # 当提交表单时
        inputText = request.POST.get('inputText',None)
        if inputText == "Hello Blueking":
            return render(request,'home_application/helloBlueking.html',{'inputText': 'Congratulation'})
        else:
            return render(request,'home_application/helloBlueking.html', {'error': True})
    else:
        return render(request, 'home_application/helloBlueking.html')

@login_exempt
def diskListenerHtml(request):
    """磁盘使用率html"""
    return render(request, 'home_application/diskListener.html')

@login_exempt
def diskListenerData(request):
    """磁盘使用率数据"""
    disks = models.DiskUsages.objects.values("disk_rate","add_time").order_by("id")
    diskLists = list(disks)
    add_times = []
    disk_rates = []
    for diskList in diskLists:
        add_times.append(str(diskList["add_time"].strftime("%Y-%m-%d %H:%M")))
        disk_rates.append(diskList["disk_rate"])
    data = {
        "code": 0,
        "result": True,
        "messge": "success",
        "data": {
            "title": "标题",
            "series": [
                {
                    "color": "#f9ce1d",
                    "name": "X轴：日期，Y轴：百分比",
                    "data": disk_rates
                }
            ],
            "categories": add_times
        }
    }

    return JsonResponse(data, safe=False)

@login_exempt
def api_disk_usage(request):
    """查询指定磁盘使用率API接口"""
    ip = request.GET.get('ip', '')
    system = request.GET.get('system', '')
    disk = request.GET.get('disk', '')
    try:
        if ip and system and disk:
            computers = models.DiskUsages.objects.filter(ip=ip, system=system, disk=disk).order_by("id")
            diskList = []
            for _i in computers:
                diskList.append({
                    'ip':_i.ip,
                    'system':_i.system,
                    'disk':_i.disk,
                    'disk_rate':_i.disk_rate,
                    'add_time':datetime.datetime.strftime(_i.add_time,'%Y-%m-%d %H:%M'),#%s
                })
            return JsonResponse({
                "code": 0,
                "result": True,
                "data": diskList,
                "message": 'success'
            })
        else:
            return JsonResponse({
                "code": -1,
                "result": False,
                "data": [],
                "message": '参数不完整'
            })
    except Exception as e:
        return JsonResponse({
            "code": -2,
            "result": False,
            "data": [],
            "message": '内部错误:%s' % e
        })

@login_exempt
def get_usage_data(request):
    """调用自主接入接口api"""
    if request.method == 'POST':
        ip = request.POST.get('ip', '')
        system = request.POST.get('system', '')
        disk = request.POST.get('disk', '')
        kwargs = {
            "ip": ip,
            "system": system,
            "disk": disk
        }
        client = get_client_by_user('277301587')
        usage = client.self_api.get_disk_usage(kwargs)
        return JsonResponse(usage)
    else:
        return render(request, 'home_application/getDiskUsage.html')

home_application/templates/home_application/diskListener.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <!-- 若您需要使用Kendo UI Professional，请联系版权人获得合法的授权或许可。 -->
    <!-- Bootstrap css -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <!-- kendo ui css -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/styles/kendo.common.min.css" rel="stylesheet">
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/styles/kendo.default.min.css" rel="stylesheet">
    <!-- font-awesome -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/fontawesome/css/font-awesome.css" rel="stylesheet">
    <!--蓝鲸提供的公用样式库 -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk.css" rel="stylesheet">
    <link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk_pack.css" rel="stylesheet">
    <!-- 如果要使用Bootstrap的js插件，必须先调入jQuery -->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/jquery-1.10.2.min.js"></script>
    <!-- 包括所有bootstrap的js插件或者可以根据需要使用的js插件调用　-->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/echarts-2.0/echarts-all.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/js/bootstrap.min.js"></script>
    <!-- 包括所有kendoui的js插件或者可以根据需要使用的js插件调用　-->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/js/kendo.all.min.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/echarts-2.0/echarts-all.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/bk/js/bk.js"></script>
    <!-- 数据埋点统计 -->
    <script src="http://magicbox.bk.tencent.com/static_api/analysis.js"></script>
    <!-- 以下两个插件用于在IE8以及以下版本浏览器支持HTML5元素和媒体查询，如果不需要用可以移除 -->
    <!--[if lt IE 9]><script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/html5shiv.min.js"></script><script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/respond.min.js"></script><![endif]-->
</head>

<body class="bg-white" data-bg-color="bg-white">
    <div class="king-page-box">
        <div class="king-container clearfix">
            <nav role="navigation" class="navbar navbar-default king-horizontal-nav2    f14 ">
                <div class="container " style="width:100%;overflow:hidden;">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed navbar-toggle-sm" data-toggle="collapse" data-target="#king-horizontal-nav2-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="javascript:;">
                            <img src="https://magicbox.bk.tencent.com/static_api/v3/bk/images/logo3.png" alt="" class="logo"> </a>
                    </div>
                    <div class="collapse navbar-collapse navbar-responsive-collapse" id="king-horizontal-nav2-collapse">
                        <ul class="nav navbar-nav">
                            <li class="king-navbar-active"><a href="{{ SITE_URL }}">首页</a></li>
                            <li class="king-navbar-active"><a href="{{ SITE_URL }}helloworld/"><span>hello world</span></a></li>
                            <li class="king-navbar-active"><a href="{{ SITE_URL }}helloBlueking/"><span>Congratulation</span></a></li>
                            <li class="king-navbar-active"><a href="{{ SITE_URL }}modelsData/"><span>MagicBox</span></a></li>
                            <li class="king-navbar-active"><a href="{{ SITE_URL }}diskListenerHtml/"><span>磁盘使用率</span></a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="javascript:;">
                                    <span>管理者</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="king-block king-block-bordered king-block-themed mb0">
                <div class="king-block-header king-info">
                    <ul class="king-block-options">
                        <li>
                            <!-- <button type="button"><i class="fa fa-cog"></i></button> -->
                        </li>
                    </ul>
                    <h3 class="king-block-title">磁盘使用率</h3>
                </div>
                <div class="king-block-content">
                    <div style="height: 300px; position: relative;" id="chart_1559803155852" class="king-chart-box chart-line  k-chart" data-role="chart"></div>
                </div>
            </div>
        </div>
    </div>
    <script>
        // 创建图表
        function createKendoLineChart(conf){
            $(conf.selector).kendoChart({
                transitions: false,
                legend: {
                   position: "bottom"
                },
                colors: ['yellow'],
                theme : 'bootstrap',
                seriesDefaults: {
                    type: 'line',
                    style: "smooth",
                    markers: {
                        visible: false
                    }
                },
                series: conf.data.series,
                categoryAxis: {
                    majorGridLines : {
                        visible: false
                    },
                    categories: conf.data.categories,
                    labels: {
                        rotation: "auto"
                    }
                },
                tooltip: {
                    visible: true,
                    template: "#= category # #= value #"
                }
            });
            //重新绘制
            $(window).on('resize',function(){
                var chart = $(conf.selector).data("kendoChart");
                chart.redraw();
            });
        }

        function initKendoLineChart(conf){
            // 异步请求后台数据
            $.ajax({
                url: conf.url,
                type: 'GET',
                dataType: conf.dataType,
                success: function(res){
                    //获取数据成功
                    if (res.result){
                        var data = {
                            series: res.data.series,
                            categories: res.data.categories
                        };
                        createKendoLineChart({
                            selector: conf.container, // 图表容器
                            data: data // 图表数据
                        });
                    }
                }
            });
        }
    </script>
    <script>
        $(function(){
            initKendoLineChart({
                url: "{% url 'framework:diskListenerData' %}",
                dataType: 'json',
                container: '#chart_1559803155852'
            });
        });
    </script>
</body>

</html>

home_application/templates/home_application/getDiskUsage.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <!-- 若您需要使用Kendo UI Professional，请联系版权人获得合法的授权或许可。 -->
    <!-- Bootstrap css -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <!-- kendo ui css -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/styles/kendo.common.min.css" rel="stylesheet">
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/styles/kendo.default.min.css" rel="stylesheet">
    <!-- font-awesome -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/assets/fontawesome/css/font-awesome.css" rel="stylesheet">
    <!--蓝鲸提供的公用样式库 -->
    <link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk.css" rel="stylesheet">
    <link href="https://magicbox.bk.tencent.com/static_api/v3/bk/css/bk_pack.css" rel="stylesheet">
    <!-- 如果要使用Bootstrap的js插件，必须先调入jQuery -->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/jquery-1.10.2.min.js"></script>
    <!-- 包括所有bootstrap的js插件或者可以根据需要使用的js插件调用　-->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/echarts-2.0/echarts-all.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/bootstrap-3.3.4/js/bootstrap.min.js"></script>
    <!-- 包括所有kendoui的js插件或者可以根据需要使用的js插件调用　-->
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/kendoui-2015.2.624/js/kendo.all.min.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/assets/echarts-2.0/echarts-all.js"></script>
    <script src="https://magicbox.bk.tencent.com/static_api/v3/bk/js/bk.js"></script>
    <!-- 数据埋点统计 -->
    <script src="http://magicbox.bk.tencent.com/static_api/analysis.js"></script>
    <!-- 以下两个插件用于在IE8以及以下版本浏览器支持HTML5元素和媒体查询，如果不需要用可以移除 -->
    <!--[if lt IE 9]><script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/html5shiv.min.js"></script><script src="https://magicbox.bk.tencent.com/static_api/v3/assets/js/respond.min.js"></script><![endif]-->
    <style>
        #diskTime li{
            cursor:pointer;
        }
    </style>
</head>

<body class="bg-white" data-bg-color="bg-white">
    <div class="king-page-box">
        <div class="king-container clearfix">
            <nav role="navigation" class="navbar navbar-default king-horizontal-nav2    f14 ">
                <div class="container " style="width:100%;overflow:hidden;">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed navbar-toggle-sm" data-toggle="collapse" data-target="#king-horizontal-nav2-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="javascript:;">
                            <img src="https://magicbox.bk.tencent.com/static_api/v3/bk/images/logo3.png" alt="" class="logo"> </a>
                    </div>
                    <div class="collapse navbar-collapse navbar-responsive-collapse" id="king-horizontal-nav2-collapse">
                        <ul class="nav navbar-nav">
                            <li class="king-navbar-active"><a href="{{ SITE_URL }}">首页</a></li>
                            <li class="king-navbar-active"><a href="{{ SITE_URL }}helloworld/"><span>hello world</span></a></li>
                            <li class="king-navbar-active"><a href="{{ SITE_URL }}helloBlueking/"><span>Congratulation</span></a></li>
                            <li class="king-navbar-active"><a href="{{ SITE_URL }}modelsData/"><span>MagicBox</span></a></li>
                            <li class="king-navbar-active"><a href="{{ SITE_URL }}diskListenerHtml/"><span>磁盘使用率</span></a></li>
                            <li class="king-navbar-active"><a href="{{ SITE_URL }}getUsageData/"><span>自定义API</span></a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="javascript:;">
                                    <span>管理者</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container-fluid mb0 ">
                <div class="row">
                    <div class="col-md-10">
                        <div class="king-panel8 m15">
                            <div class="king-panel8-header">
                                <h3 class="king-panel8-title king-info">磁盘使用率查询参数</h3>
                            </div>
                            <div class="king-panel8-content pt25">
                                <form class="form-horizontal" id="getFormData">
                                     {% csrf_token %}
                                    <div class="form-group clearfix ">
                                        <label class="col-sm-3 control-label bk-lh30 pt0">IP地址：</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control bk-valign-top" name="ip" placeholder="如：127.0.0.1,10.0.1.80"> </div>
                                    </div>
                                    <div class="form-group clearfix ">
                                        <label class="control-label col-sm-3 bk-lh30 pt0">使用系统：</label>
                                        <div class="col-sm-9">
                                            <div class="radio pt0">
                                                <label class="mr10">
                                                    <input type="radio" name="system" id="" class="bk-top5" value="windows" checked="checked">
                                                    <span class="bk-lh30">windows</span>
                                                </label>
                                                <label class="mr10">
                                                    <input type="radio" name="system" id="" class="bk-top5" value="linux">
                                                    <span class="bk-lh30">linux</span>
                                                </label>
                                                <label class="mr10">
                                                    <input type="radio" name="system" id="" class="bk-top5" value="macOS">
                                                    <span class="bk-lh30">macOS</span>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group clearfix ">
                                        <label class="col-sm-3 control-label bk-lh30 pt0">磁盘：</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control bk-valign-top" name="disk" placeholder="如：C"> </div>
                                    </div>
                                    <div class="form-group clearfix">
                                        <div class="col-sm-9 col-sm-offset-3">
                                            <button type="button" class="king-btn mr10  king-success" id="submitData">查询</button>
                                            <button type="reset" class="king-btn king-default ">重置</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="king-panel8 m15">
                <div class="king-panel8-header">
                    <h3 class="king-panel8-title king-info">磁盘使用率结果</h3>
                </div>
                <div class="king-panel8-content pt25">
                    <div style="height: 300px; position: relative;" id="chart_1560496773217" class="king-chart-box chart-line  k-chart" data-role="chart"></div>
                </div>
                </div>
                    </div>
                    <div class="col-md-2">
                        <div class="king-panel8 m15">
                            <div class="king-panel8-header">
                                <h3 class="king-panel8-title king-info">磁盘查询时间轴</h3>
                            </div>
                            <div class="king-panel8-content pt25" id="diskScript">
                                <ul class="king-timeline-simple" id="diskTime"></ul>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        // 创建图表
        function createKendoLineChart(conf){
            $(conf.selector).kendoChart({
                transitions: false,
                legend: {
                   position: "bottom"
                },
                colors: ['yellow'],
                theme : 'bootstrap',
                seriesDefaults: {
                    type: 'line',
                    style: "smooth",
                    markers: {
                        visible: false
                    }
                },
                series: conf.data.series,
                categoryAxis: {
                    majorGridLines : {
                        visible: false
                    },
                    categories: conf.data.categories,
                    labels: {
                        rotation: "auto"
                    }
                },
                tooltip: {
                    visible: true,
                    template: "#= category # #= value #"
                }
            });
            //重新绘制
            $(window).on('resize',function(){
                var chart = $(conf.selector).data("kendoChart");
                chart.redraw();
            });
        }
        var jsondata = {};
        $("#submitData").click(function(){ // 查询调用接口
            var datas = $('#getFormData').serialize();
            $.ajax({
                url: "{% url 'framework:getUsageData' %}",
                type: 'post',
                dataType:'json',
                data: datas,
                success: function(res){
                    diskResult(res);
                 }
            });
        });
        function diskResult(res) {  // 获取查询日期集合
            if (res.result){
                diskUsage(res.data);
                keys = [];
                for (var key in jsondata) {
                    keys.push(key);
                }
                diskTimes(keys);
                defaultDisk(jsondata[keys[0]], keys[0]); // 默认加载第一个数据
            }
        }
        function defaultDisk(queryTime, defaultTime) { // 展示的数据
            defaultRates = [];
            defaultTimes = [];
            for (j = 0,len=queryTime.length; j < len; j++){
                defaultRates.push(queryTime[j].disk_rate);
                defaultTimes.push(queryTime[j].add_time);
            }
            var data = {
                series:  [{"color": "#f9ce1d", "name": defaultTime+" 磁盘使用率", "data": defaultRates}],
                categories: defaultTimes
            };
            createKendoLineChart({
                selector: '#chart_1560496773217', // 图表容器
                data: data // 图表数据
            });
        }
        function diskTimes(times) { // 时间轴
            var _html = "";
            for (j = 0,len=times.length; j < len; j++) {
                var liTime = times[j];
                var aTime = liTime.replace(/\-/g,"");;
                _html = _html+"<li class='info' id='diskData_"+aTime+"'> <div class=''> 查询日期 <span class='timeline-simple-date'>"+liTime+"</span></div></li>";
            }
            $("#diskTime").html(_html);
            onDiskClick();
        }
        function onDiskClick() { // 给时间轴绑定点击事件
            var _clickJS = '<script>';
            for (var key in jsondata) {
                var strKey = key.replace(/\-/g,"");
                 _clickJS = _clickJS + '$("#diskTime").on("click","'+'#diskData_'+strKey+'",function(){defaultDisk(jsondata["'+key+'"], "'+key+'");});\n'
            }
            _clickJS = _clickJS + '<\/script>';
            $("#diskScript").after(_clickJS);
        }

        function diskUsage(datas) { // 对返回的数据按日期分组
            for (j = 0,len=datas.length; j < len; j++) {
                var strTime = datas[j].add_time;
                var thisDate = strTime.split(" ")[0];
                var thisTime = strTime.split(" ")[1];
                if (jsondata[thisDate]) {
                    jsondata[thisDate].push({"add_time": thisTime, "disk_rate": datas[j].disk_rate});
                }else {
                    jsondata[thisDate]=[{"add_time": thisTime, "disk_rate": datas[j].disk_rate}];
                }
            }
        }

    </script>
</body>

</html>